"""add source_filename to generationjob

Revision ID: 11fb6b73b709
Revises: 1c4cc0f6afa2
Create Date: 2026-08-31 14:18:01.183023

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '11fb6b73b709'
down_revision = '1c4cc0f6afa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generationjob', sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generationjob', 'source_filename')
    # ### end Alembic commands ###
