"""add classroom_snapshot to generationjob

Revision ID: 24f411eb18ca
Revises: 9a3d16a27e1a
Create Date: 2026-09-02 12:09:56.854765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '24f411eb18ca'
down_revision = '9a3d16a27e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generationjob', sa.Column('classroom_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generationjob', 'classroom_snapshot')
    # ### end Alembic commands ###
