"""add title to generationjob

Revision ID: 9a3d16a27e1a
Revises: ede49a03c6ba
Create Date: 2026-09-01 15:39:18.474534

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a3d16a27e1a'
down_revision = 'ede49a03c6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generationjob', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generationjob', 'title')
    # ### end Alembic commands ###
