"""add user role, enrollments, chapter progress, course enroll code

Revision ID: 9a891ad6140b
Revises: 11fb6b73b709
Create Date: 2026-08-31 14:58:04.582633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a891ad6140b'
down_revision = '11fb6b73b709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapterprogress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('course', sa.Column('enroll_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    # Backfill enroll codes for existing courses
    import secrets
    import string
    alphabet = string.ascii_uppercase + string.digits
    conn = op.get_bind()
    course_ids = [row[0] for row in conn.execute(sa.text('SELECT id FROM course')).fetchall()]
    for cid in course_ids:
        code = ''.join(secrets.choice(alphabet) for _ in range(8))
        conn.execute(sa.text('UPDATE course SET enroll_code = :code WHERE id = :cid'), {'code': code, 'cid': cid})
    op.create_index(op.f('ix_course_enroll_code'), 'course', ['enroll_code'], unique=True)
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='student'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_course_enroll_code'), table_name='course')
    op.drop_column('course', 'enroll_code')
    op.drop_table('chapterprogress')
    op.drop_table('enrollment')
    # ### end Alembic commands ###
