"""add publish state and edited snapshot to generationjob

Revision ID: c5182cd23d0f
Revises: 9a891ad6140b
Create Date: 2026-08-31 15:21:31.633713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5182cd23d0f'
down_revision = '9a891ad6140b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generationjob', sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('generationjob', sa.Column('edited_classroom', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generationjob', 'edited_classroom')
    op.drop_column('generationjob', 'is_published')
    # ### end Alembic commands ###
