/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCoursesRouteImport } from './routes/_layout/courses'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutJoinRouteImport } from './routes/_layout/join'
import { Route as LayoutLearningDataRouteImport } from './routes/_layout/learning-data'
import { Route as LayoutMyCoursesRouteImport } from './routes/_layout/my-courses'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutStudentRouteImport } from './routes/_layout/student'
import { Route as LayoutStudentsRouteImport } from './routes/_layout/students'
import { Route as LayoutTeacherRouteImport } from './routes/_layout/teacher'
import { Route as LayoutCoursesIndexRouteImport } from './routes/_layout/courses.index'
import { Route as LayoutCoursesCourseIdRouteImport } from './routes/_layout/courses.$courseId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesRoute = LayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJoinRoute = LayoutJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearningDataRoute = LayoutLearningDataRouteImport.update({
  id: '/learning-data',
  path: '/learning-data',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyCoursesRoute = LayoutMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentRoute = LayoutStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStudentsRoute = LayoutStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeacherRoute = LayoutTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCoursesIndexRoute = LayoutCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCoursesRoute,
} as any)
const LayoutCoursesCourseIdRoute = LayoutCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => LayoutCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/courses': typeof LayoutCoursesRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/join': typeof LayoutJoinRoute
  '/learning-data': typeof LayoutLearningDataRoute
  '/my-courses': typeof LayoutMyCoursesRoute
  '/settings': typeof LayoutSettingsRoute
  '/student': typeof LayoutStudentRoute
  '/students': typeof LayoutStudentsRoute
  '/teacher': typeof LayoutTeacherRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdRoute
  '/courses/': typeof LayoutCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/join': typeof LayoutJoinRoute
  '/learning-data': typeof LayoutLearningDataRoute
  '/my-courses': typeof LayoutMyCoursesRoute
  '/settings': typeof LayoutSettingsRoute
  '/student': typeof LayoutStudentRoute
  '/students': typeof LayoutStudentsRoute
  '/teacher': typeof LayoutTeacherRoute
  '/': typeof LayoutIndexRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdRoute
  '/courses': typeof LayoutCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/courses': typeof LayoutCoursesRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/join': typeof LayoutJoinRoute
  '/_layout/learning-data': typeof LayoutLearningDataRoute
  '/_layout/my-courses': typeof LayoutMyCoursesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/student': typeof LayoutStudentRoute
  '/_layout/students': typeof LayoutStudentsRoute
  '/_layout/teacher': typeof LayoutTeacherRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/courses/$courseId': typeof LayoutCoursesCourseIdRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/courses'
    | '/items'
    | '/join'
    | '/learning-data'
    | '/my-courses'
    | '/settings'
    | '/student'
    | '/students'
    | '/teacher'
    | '/courses/$courseId'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/join'
    | '/learning-data'
    | '/my-courses'
    | '/settings'
    | '/student'
    | '/students'
    | '/teacher'
    | '/'
    | '/courses/$courseId'
    | '/courses'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/courses'
    | '/_layout/items'
    | '/_layout/join'
    | '/_layout/learning-data'
    | '/_layout/my-courses'
    | '/_layout/settings'
    | '/_layout/student'
    | '/_layout/students'
    | '/_layout/teacher'
    | '/_layout/'
    | '/_layout/courses/$courseId'
    | '/_layout/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/join': {
      id: '/_layout/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof LayoutJoinRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learning-data': {
      id: '/_layout/learning-data'
      path: '/learning-data'
      fullPath: '/learning-data'
      preLoaderRoute: typeof LayoutLearningDataRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-courses': {
      id: '/_layout/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof LayoutMyCoursesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/student': {
      id: '/_layout/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof LayoutStudentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/students': {
      id: '/_layout/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof LayoutStudentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teacher': {
      id: '/_layout/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof LayoutTeacherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutCoursesIndexRouteImport
      parentRoute: typeof LayoutCoursesRoute
    }
    '/_layout/courses/$courseId': {
      id: '/_layout/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdRouteImport
      parentRoute: typeof LayoutCoursesRoute
    }
  }
}

interface LayoutCoursesRouteChildren {
  LayoutCoursesCourseIdRoute: typeof LayoutCoursesCourseIdRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
}

const LayoutCoursesRouteChildren: LayoutCoursesRouteChildren = {
  LayoutCoursesCourseIdRoute: LayoutCoursesCourseIdRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
}

const LayoutCoursesRouteWithChildren = LayoutCoursesRoute._addFileChildren(
  LayoutCoursesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCoursesRoute: typeof LayoutCoursesRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutJoinRoute: typeof LayoutJoinRoute
  LayoutLearningDataRoute: typeof LayoutLearningDataRoute
  LayoutMyCoursesRoute: typeof LayoutMyCoursesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStudentRoute: typeof LayoutStudentRoute
  LayoutStudentsRoute: typeof LayoutStudentsRoute
  LayoutTeacherRoute: typeof LayoutTeacherRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCoursesRoute: LayoutCoursesRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutJoinRoute: LayoutJoinRoute,
  LayoutLearningDataRoute: LayoutLearningDataRoute,
  LayoutMyCoursesRoute: LayoutMyCoursesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStudentRoute: LayoutStudentRoute,
  LayoutStudentsRoute: LayoutStudentsRoute,
  LayoutTeacherRoute: LayoutTeacherRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
