import { existsSync, mkdtempSync, readFileSync } from 'fs';
import os from 'os';
import path from 'path';
import { beforeEach, describe, expect, it, vi } from 'vitest';

/**
 * /api/generate/tts persists generated bytes beside the classroom when the
 * request names one, so browser-regenerated narration survives server-side and
 * other browsers (the student embed) can fetch it through classroom-media.
 */
describe('POST /api/generate/tts server-side persistence', () => {
  let classroomsDir: string;

  beforeEach(() => {
    vi.resetModules();
    classroomsDir = mkdtempSync(path.join(os.tmpdir(), 'classrooms-tts-'));
    process.env.CLASSROOMS_DATA_DIR = classroomsDir;
    vi.doMock('@/lib/audio/tts-providers', () => {
      class TTSRateLimitError extends Error {}
      return {
        TTSRateLimitError,
        generateTTS: vi.fn().mockResolvedValue({
          audio: Buffer.from('RIFF-fake-bytes'),
          format: 'wav',
        }),
      };
    });
    vi.doMock('@/lib/server/usage-storage', () => ({
      recordGenerationUsage: vi.fn().mockResolvedValue(undefined),
    }));
  });

  async function callRoute(body: Record<string, unknown>) {
    const { POST } = await import('@/app/api/generate/tts/route');
    const request = new Request('http://localhost/api/generate/tts', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-forwarded-host': 'teacher.example',
        'x-forwarded-proto': 'https',
      },
      body: JSON.stringify(body),
    });
    const response = await POST(request as never);
    return { response, json: (await response.json()) as Record<string, unknown> };
  }

  const baseBody = {
    text: '同学们好',
    ttsProviderId: 'qwen-tts',
    ttsVoice: 'Cherry',
    ttsApiKey: 'test-key',
  };

  it('writes the audio file and returns the serving URL', async () => {
    const { response, json } = await callRoute({
      ...baseBody,
      audioId: 'tts_request_s1_action_intro',
      classroomId: 'cls_9',
    });

    expect(response.status).toBe(200);
    const data = json as { audioUrl?: string; base64?: string };
    const file = path.join(classroomsDir, 'cls_9', 'audio', 'tts_s1_action_intro.wav');
    expect(existsSync(file)).toBe(true);
    expect(readFileSync(file).toString()).toBe('RIFF-fake-bytes');
    expect(data.audioUrl).toMatch(
      /^https:\/\/teacher\.example\/api\/classroom-media\/cls_9\/audio\/tts_s1_action_intro\.wav\?v=[0-9a-f]{12}$/,
    );
    expect(data.base64).toBeTruthy();
  });

  it('skips persistence for an invalid classroom id or unsafe audio id', async () => {
    const badClassroom = await callRoute({
      ...baseBody,
      audioId: 'tts_request_s1_action_x',
      classroomId: '../evil',
    });
    expect((badClassroom.json as { audioUrl?: string }).audioUrl).toBeUndefined();

    const badAudioId = await callRoute({
      ...baseBody,
      audioId: 'tts_request_../../etc/passwd',
      classroomId: 'cls_9',
    });
    expect((badAudioId.json as { audioUrl?: string }).audioUrl).toBeUndefined();
    // No directory outside the classrooms root was touched.
    expect(existsSync(path.join(classroomsDir, 'cls_9', 'audio'))).toBe(false);
  });

  it('still returns audio when no classroom is named', async () => {
    const { response, json } = await callRoute({
      ...baseBody,
      audioId: 'tts_s1_action_plain',
    });
    expect(response.status).toBe(200);
    expect((json as { base64?: string }).base64).toBeTruthy();
    expect((json as { audioUrl?: string }).audioUrl).toBeUndefined();
  });
});
