// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AgentMessageRequest
 *
 * One send: the newest user-role message plus the consistency assertion.
 */
export type AgentMessageRequest = {
    /**
     * Agent Key
     */
    agent_key: string;
    /**
     * Scope Type
     */
    scope_type: string;
    /**
     * Scope Id
     */
    scope_id: string;
    /**
     * Messages
     */
    messages: Array<Message_Input>;
};

/**
 * AgentSessionCreateRequest
 *
 * Explicit new-session creation; ``idempotency_key`` dedups retries.
 */
export type AgentSessionCreateRequest = {
    /**
     * Agent Key
     */
    agent_key: string;
    scope: AgentSessionScope;
    /**
     * Idempotency Key
     */
    idempotency_key?: string | null;
};

/**
 * AgentSessionPublic
 */
export type AgentSessionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Agent Key
     */
    agent_key: string;
    /**
     * Scope Type
     */
    scope_type: string;
    /**
     * Scope Id
     */
    scope_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * AgentSessionResolveRequest
 *
 * Read-only "which session should I show" lookup — no creation side effect.
 */
export type AgentSessionResolveRequest = {
    /**
     * Agent Key
     */
    agent_key: string;
    scope: AgentSessionScope;
    /**
     * Preferred Session Id
     */
    preferred_session_id?: string | null;
};

/**
 * AgentSessionScope
 *
 * The business object a session lives under, as the client states it.
 *
 * Both fields are untrusted input until the backend loads the real object
 * through the scope adapter (plan §4.2).
 */
export type AgentSessionScope = {
    /**
     * Type
     */
    type: string;
    /**
     * Id
     */
    id: string;
};

/**
 * AgentSessionUpdateRequest
 *
 * Manual title rename.
 */
export type AgentSessionUpdateRequest = {
    /**
     * Title
     */
    title: string;
};

/**
 * AgentSessionsPublic
 */
export type AgentSessionsPublic = {
    /**
     * Data
     */
    data: Array<AgentSessionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChapterCreate
 */
export type ChapterCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Order Index
     */
    order_index?: number;
};

/**
 * ChapterPublic
 */
export type ChapterPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Order Index
     */
    order_index?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Course Id
     */
    course_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Completed
     */
    completed?: boolean | null;
};

/**
 * ChapterUpdate
 */
export type ChapterUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Order Index
     */
    order_index?: number | null;
};

/**
 * ChaptersPublic
 */
export type ChaptersPublic = {
    /**
     * Data
     */
    data: Array<ChapterPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ChatResponse
 *
 * Response payload for the non-streaming chat endpoint.
 */
export type ChatResponse = {
    /**
     * Messages
     *
     * List of messages in the reply
     */
    messages: Array<HistoryMessage>;
};

/**
 * CourseCreate
 */
export type CourseCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CoursePublic
 */
export type CoursePublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Enroll Code
     */
    enroll_code?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CourseUpdate
 */
export type CourseUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * CoursesPublic
 */
export type CoursesPublic = {
    /**
     * Data
     */
    data: Array<CoursePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EnrollByCode
 */
export type EnrollByCode = {
    /**
     * Code
     */
    code: string;
};

/**
 * EnrolledCoursePublic
 */
export type EnrolledCoursePublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Enroll Code
     */
    enroll_code?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Total Chapters
     */
    total_chapters?: number;
    /**
     * Completed Chapters
     */
    completed_chapters?: number;
};

/**
 * EnrolledCoursesPublic
 */
export type EnrolledCoursesPublic = {
    /**
     * Data
     */
    data: Array<EnrolledCoursePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HistoryMessage
 *
 * A message returned from the agent (chat history or reply).
 *
 * Distinct from :class:`Message` on purpose: the input model enforces the
 * 1-3000 length cap and script-tag hygiene on *user* input, while model
 * replies and checkpoint history legitimately exceed that cap. Sharing one
 * model made ``__process_messages`` raise on long replies (migration
 * inventory gap #1).
 */
export type HistoryMessage = {
    /**
     * Role
     *
     * The role of the message sender
     */
    role: 'user' | 'assistant';
    /**
     * Content
     *
     * The content of the message
     */
    content: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 *
 * A single chat message crossing the API boundary.
 */
export type Message_Input = {
    /**
     * Role
     *
     * The role of the message sender
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * The content of the message
     */
    content: string;
};

/**
 * Message
 */
export type Message_Output = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OutlineImportHint
 *
 * One (course, thread) pair reported from a teacher's localStorage.
 */
export type OutlineImportHint = {
    /**
     * Course Id
     */
    course_id: string;
    /**
     * Thread Uuid
     */
    thread_uuid: string;
};

/**
 * OutlineImportRequest
 *
 * One-shot legacy outline thread report (plan §8.2, decision 12.7).
 */
export type OutlineImportRequest = {
    /**
     * Hints
     */
    hints: Array<OutlineImportHint>;
};

/**
 * OutlineImportResult
 */
export type OutlineImportResult = {
    /**
     * Imported
     */
    imported: number;
    /**
     * Skipped
     */
    skipped: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SendVerificationCode
 */
export type SendVerificationCode = {
    /**
     * Email
     */
    email: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Role
     */
    role?: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Role
     */
    role?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Role
     */
    role?: 'student' | 'teacher';
    /**
     * Code
     */
    code: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersSendVerificationCodeData = {
    body: SendVerificationCode;
    path?: never;
    query?: never;
    url: '/api/v1/users/send-verification-code';
};

export type usersSendVerificationCodeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersSendVerificationCodeError = usersSendVerificationCodeErrors[keyof usersSendVerificationCodeErrors];

export type usersSendVerificationCodeResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type usersSendVerificationCodeResponse = usersSendVerificationCodeResponses[keyof usersSendVerificationCodeResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message_Output;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type coursesReadCoursesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/courses/';
};

export type coursesReadCoursesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesReadCoursesError = coursesReadCoursesErrors[keyof coursesReadCoursesErrors];

export type coursesReadCoursesResponses = {
    /**
     * Successful Response
     */
    200: CoursesPublic;
};

export type coursesReadCoursesResponse = coursesReadCoursesResponses[keyof coursesReadCoursesResponses];

export type coursesCreateCourseData = {
    body: CourseCreate;
    path?: never;
    query?: never;
    url: '/api/v1/courses/';
};

export type coursesCreateCourseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesCreateCourseError = coursesCreateCourseErrors[keyof coursesCreateCourseErrors];

export type coursesCreateCourseResponses = {
    /**
     * Successful Response
     */
    200: CoursePublic;
};

export type coursesCreateCourseResponse = coursesCreateCourseResponses[keyof coursesCreateCourseResponses];

export type coursesDeleteCourseData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/v1/courses/{course_id}';
};

export type coursesDeleteCourseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesDeleteCourseError = coursesDeleteCourseErrors[keyof coursesDeleteCourseErrors];

export type coursesDeleteCourseResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type coursesDeleteCourseResponse = coursesDeleteCourseResponses[keyof coursesDeleteCourseResponses];

export type coursesReadCourseData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/v1/courses/{course_id}';
};

export type coursesReadCourseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesReadCourseError = coursesReadCourseErrors[keyof coursesReadCourseErrors];

export type coursesReadCourseResponses = {
    /**
     * Successful Response
     */
    200: CoursePublic;
};

export type coursesReadCourseResponse = coursesReadCourseResponses[keyof coursesReadCourseResponses];

export type coursesUpdateCourseData = {
    body: CourseUpdate;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/v1/courses/{course_id}';
};

export type coursesUpdateCourseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesUpdateCourseError = coursesUpdateCourseErrors[keyof coursesUpdateCourseErrors];

export type coursesUpdateCourseResponses = {
    /**
     * Successful Response
     */
    200: CoursePublic;
};

export type coursesUpdateCourseResponse = coursesUpdateCourseResponses[keyof coursesUpdateCourseResponses];

export type coursesReadChaptersData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/courses/{course_id}/chapters';
};

export type coursesReadChaptersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesReadChaptersError = coursesReadChaptersErrors[keyof coursesReadChaptersErrors];

export type coursesReadChaptersResponses = {
    /**
     * Successful Response
     */
    200: ChaptersPublic;
};

export type coursesReadChaptersResponse = coursesReadChaptersResponses[keyof coursesReadChaptersResponses];

export type coursesCreateChapterData = {
    body: ChapterCreate;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/v1/courses/{course_id}/chapters';
};

export type coursesCreateChapterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesCreateChapterError = coursesCreateChapterErrors[keyof coursesCreateChapterErrors];

export type coursesCreateChapterResponses = {
    /**
     * Successful Response
     */
    200: ChapterPublic;
};

export type coursesCreateChapterResponse = coursesCreateChapterResponses[keyof coursesCreateChapterResponses];

export type coursesDeleteChapterData = {
    body?: never;
    path: {
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/courses/chapters/{chapter_id}';
};

export type coursesDeleteChapterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesDeleteChapterError = coursesDeleteChapterErrors[keyof coursesDeleteChapterErrors];

export type coursesDeleteChapterResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type coursesDeleteChapterResponse = coursesDeleteChapterResponses[keyof coursesDeleteChapterResponses];

export type coursesUpdateChapterData = {
    body: ChapterUpdate;
    path: {
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/courses/chapters/{chapter_id}';
};

export type coursesUpdateChapterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesUpdateChapterError = coursesUpdateChapterErrors[keyof coursesUpdateChapterErrors];

export type coursesUpdateChapterResponses = {
    /**
     * Successful Response
     */
    200: ChapterPublic;
};

export type coursesUpdateChapterResponse = coursesUpdateChapterResponses[keyof coursesUpdateChapterResponses];

export type coursesUncompleteChapterData = {
    body?: never;
    path: {
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/courses/chapters/{chapter_id}/complete';
};

export type coursesUncompleteChapterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesUncompleteChapterError = coursesUncompleteChapterErrors[keyof coursesUncompleteChapterErrors];

export type coursesUncompleteChapterResponses = {
    /**
     * Successful Response
     */
    200: ChapterPublic;
};

export type coursesUncompleteChapterResponse = coursesUncompleteChapterResponses[keyof coursesUncompleteChapterResponses];

export type coursesCompleteChapterData = {
    body?: never;
    path: {
        /**
         * Chapter Id
         */
        chapter_id: string;
    };
    query?: never;
    url: '/api/v1/courses/chapters/{chapter_id}/complete';
};

export type coursesCompleteChapterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type coursesCompleteChapterError = coursesCompleteChapterErrors[keyof coursesCompleteChapterErrors];

export type coursesCompleteChapterResponses = {
    /**
     * Successful Response
     */
    200: ChapterPublic;
};

export type coursesCompleteChapterResponse = coursesCompleteChapterResponses[keyof coursesCompleteChapterResponses];

export type enrollmentsJoinCourseData = {
    body: EnrollByCode;
    path?: never;
    query?: never;
    url: '/api/v1/enrollments/join';
};

export type enrollmentsJoinCourseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type enrollmentsJoinCourseError = enrollmentsJoinCourseErrors[keyof enrollmentsJoinCourseErrors];

export type enrollmentsJoinCourseResponses = {
    /**
     * Successful Response
     */
    200: EnrolledCoursePublic;
};

export type enrollmentsJoinCourseResponse = enrollmentsJoinCourseResponses[keyof enrollmentsJoinCourseResponses];

export type enrollmentsReadMyCoursesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/enrollments/my-courses';
};

export type enrollmentsReadMyCoursesResponses = {
    /**
     * Successful Response
     */
    200: EnrolledCoursesPublic;
};

export type enrollmentsReadMyCoursesResponse = enrollmentsReadMyCoursesResponses[keyof enrollmentsReadMyCoursesResponses];

export type enrollmentsLeaveCourseData = {
    body?: never;
    path: {
        /**
         * Course Id
         */
        course_id: string;
    };
    query?: never;
    url: '/api/v1/enrollments/{course_id}';
};

export type enrollmentsLeaveCourseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type enrollmentsLeaveCourseError = enrollmentsLeaveCourseErrors[keyof enrollmentsLeaveCourseErrors];

export type enrollmentsLeaveCourseResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type enrollmentsLeaveCourseResponse = enrollmentsLeaveCourseResponses[keyof enrollmentsLeaveCourseResponses];

export type agentSessionsListAgentSessionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Agent Key
         */
        agent_key: string;
        /**
         * Scope Type
         */
        scope_type: string;
        /**
         * Scope Id
         */
        scope_id: string;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/agent-sessions';
};

export type agentSessionsListAgentSessionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsListAgentSessionsError = agentSessionsListAgentSessionsErrors[keyof agentSessionsListAgentSessionsErrors];

export type agentSessionsListAgentSessionsResponses = {
    /**
     * Successful Response
     */
    200: AgentSessionsPublic;
};

export type agentSessionsListAgentSessionsResponse = agentSessionsListAgentSessionsResponses[keyof agentSessionsListAgentSessionsResponses];

export type agentSessionsCreateAgentSessionData = {
    body: AgentSessionCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agent-sessions';
};

export type agentSessionsCreateAgentSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsCreateAgentSessionError = agentSessionsCreateAgentSessionErrors[keyof agentSessionsCreateAgentSessionErrors];

export type agentSessionsCreateAgentSessionResponses = {
    /**
     * Successful Response
     */
    201: AgentSessionPublic;
};

export type agentSessionsCreateAgentSessionResponse = agentSessionsCreateAgentSessionResponses[keyof agentSessionsCreateAgentSessionResponses];

export type agentSessionsResolveAgentSessionData = {
    body: AgentSessionResolveRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agent-sessions/resolve';
};

export type agentSessionsResolveAgentSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsResolveAgentSessionError = agentSessionsResolveAgentSessionErrors[keyof agentSessionsResolveAgentSessionErrors];

export type agentSessionsResolveAgentSessionResponses = {
    /**
     * Response Agent-Sessions-Resolve Agent Session
     *
     * Successful Response
     */
    200: AgentSessionPublic | null;
};

export type agentSessionsResolveAgentSessionResponse = agentSessionsResolveAgentSessionResponses[keyof agentSessionsResolveAgentSessionResponses];

export type agentSessionsDeleteAgentSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Agent Key
         */
        agent_key: string;
        /**
         * Scope Type
         */
        scope_type: string;
        /**
         * Scope Id
         */
        scope_id: string;
    };
    url: '/api/v1/agent-sessions/{session_id}';
};

export type agentSessionsDeleteAgentSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsDeleteAgentSessionError = agentSessionsDeleteAgentSessionErrors[keyof agentSessionsDeleteAgentSessionErrors];

export type agentSessionsDeleteAgentSessionResponses = {
    /**
     * Successful Response
     */
    200: Message_Output;
};

export type agentSessionsDeleteAgentSessionResponse = agentSessionsDeleteAgentSessionResponses[keyof agentSessionsDeleteAgentSessionResponses];

export type agentSessionsReadAgentSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Agent Key
         */
        agent_key: string;
        /**
         * Scope Type
         */
        scope_type: string;
        /**
         * Scope Id
         */
        scope_id: string;
    };
    url: '/api/v1/agent-sessions/{session_id}';
};

export type agentSessionsReadAgentSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsReadAgentSessionError = agentSessionsReadAgentSessionErrors[keyof agentSessionsReadAgentSessionErrors];

export type agentSessionsReadAgentSessionResponses = {
    /**
     * Successful Response
     */
    200: AgentSessionPublic;
};

export type agentSessionsReadAgentSessionResponse = agentSessionsReadAgentSessionResponses[keyof agentSessionsReadAgentSessionResponses];

export type agentSessionsUpdateAgentSessionData = {
    body: AgentSessionUpdateRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Agent Key
         */
        agent_key: string;
        /**
         * Scope Type
         */
        scope_type: string;
        /**
         * Scope Id
         */
        scope_id: string;
    };
    url: '/api/v1/agent-sessions/{session_id}';
};

export type agentSessionsUpdateAgentSessionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsUpdateAgentSessionError = agentSessionsUpdateAgentSessionErrors[keyof agentSessionsUpdateAgentSessionErrors];

export type agentSessionsUpdateAgentSessionResponses = {
    /**
     * Successful Response
     */
    200: AgentSessionPublic;
};

export type agentSessionsUpdateAgentSessionResponse = agentSessionsUpdateAgentSessionResponses[keyof agentSessionsUpdateAgentSessionResponses];

export type agentSessionsReadAgentSessionMessagesData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Agent Key
         */
        agent_key: string;
        /**
         * Scope Type
         */
        scope_type: string;
        /**
         * Scope Id
         */
        scope_id: string;
    };
    url: '/api/v1/agent-sessions/{session_id}/messages';
};

export type agentSessionsReadAgentSessionMessagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsReadAgentSessionMessagesError = agentSessionsReadAgentSessionMessagesErrors[keyof agentSessionsReadAgentSessionMessagesErrors];

export type agentSessionsReadAgentSessionMessagesResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type agentSessionsReadAgentSessionMessagesResponse = agentSessionsReadAgentSessionMessagesResponses[keyof agentSessionsReadAgentSessionMessagesResponses];

export type agentSessionsSendAgentSessionMessageData = {
    body: AgentMessageRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/agent-sessions/{session_id}/messages';
};

export type agentSessionsSendAgentSessionMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsSendAgentSessionMessageError = agentSessionsSendAgentSessionMessageErrors[keyof agentSessionsSendAgentSessionMessageErrors];

export type agentSessionsSendAgentSessionMessageResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type agentSessionsSendAgentSessionMessageResponse = agentSessionsSendAgentSessionMessageResponses[keyof agentSessionsSendAgentSessionMessageResponses];

export type agentSessionsSendAgentSessionMessageStreamData = {
    body: AgentMessageRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/v1/agent-sessions/{session_id}/messages/stream';
};

export type agentSessionsSendAgentSessionMessageStreamErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsSendAgentSessionMessageStreamError = agentSessionsSendAgentSessionMessageStreamErrors[keyof agentSessionsSendAgentSessionMessageStreamErrors];

export type agentSessionsSendAgentSessionMessageStreamResponses = {
    /**
     * Response Agent-Sessions-Send Agent Session Message Stream
     *
     * Successful Response
     */
    200: unknown;
};

export type agentSessionsImportOutlineHintsData = {
    body: OutlineImportRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agent-sessions/outline/import-hints';
};

export type agentSessionsImportOutlineHintsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentSessionsImportOutlineHintsError = agentSessionsImportOutlineHintsErrors[keyof agentSessionsImportOutlineHintsErrors];

export type agentSessionsImportOutlineHintsResponses = {
    /**
     * Successful Response
     */
    200: OutlineImportResult;
};

export type agentSessionsImportOutlineHintsResponse = agentSessionsImportOutlineHintsResponses[keyof agentSessionsImportOutlineHintsResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
